apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snake-ingress
  namespace: games
spec:
  rules:
    - host: snake.if-then-els.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: snake
                port:
                  name: web
---
apiVersion: v1
kind: Service
metadata:
  name: snake
  namespace: games
spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: snake
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: snake
  namespace: games
  labels:
    app: snake

spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake
  template:
    metadata:
      labels:
        app: snake
    spec:
      containers:
        - name: snake
          image: gummelhummel/snake
          ports:
            - name: web
              containerPort: 80
      imagePullSecrets:
        - name: dockerhub
